create database riding;
use riding;
select * from ride;

 # Uber Ride Booking — SQL Analysis 

#1. What is the total number of bookings?
select count(*) as total_bookings from ride;

#2. How many bookings are there for each booking status?
select count(*),`Booking Status` from ride
group by `Booking Status`
order by count(*) desc;

#3. Which vehicle type has the highest number of bookings?
select `vehicle Type`,count(*)as total from ride
group by `vehicle Type`
order by total desc;

#4. What is the total booking value?
select sum(`Booking Value`) from ride;

#5. What is the average booking value?
select avg(`Booking Value`) from ride;

#6. How many successful bookings are there?
select count(*) from ride
where `Booking Status`='completed';

# Ride Analysis

#7. What is the average ride distance?
select avg(`Ride distance`) from ride;

#8. What is the maximum ride distance?
select max(`Ride distance`) from ride;

#9. What is the average ride distance for each vehicle type?
select avg(`ride distance`) as average_distance,`Vehicle Type` from ride
group by `Vehicle Type`
order by  average_distance desc;

#10. Which vehicle type has the highest average ride distance?
select `Vehicle Type` ,avg(`Ride Distance`)as highest_avg from ride
group by `Vehicle Type`
order by  highest_avg desc
limit 1;

# Cancellation Analysis
#11. How many rides were cancelled by customers?
select  count(  `cancelled rides by customer`) from ride
where `cancelled rides by customer`=1;

#12. How many rides were cancelled by drivers?
select count(`cancelled rides by driver`) from ride
where `cancelled rides by driver`=1;

#13. What are the most common customer cancellation reasons?
select  count(`Reason for CancelLing by Customer`),`Reason for CancelLing by Customer` from ride
group by `Reason for CancelLing  by Customer`;

#14. What are the most common driver cancellation reasons?
SELECT count(`Driver Cancellation Reason`),`Driver Cancellation Reason` from ride
group by `Driver Cancellation Reason`;

#15. How many rides were incomplete?
SELECT COUNT(*) as incomplete_ride FROM RIDE
where `incomplete rides`=1;

#16. What are the common reasons for incomplete rides?
select `Incomplete rides reason` ,count(*)as total from ride
group by `Incomplete rides reason`
order by total desc;

# Location Analysis

#17. What are the top 10 pickup locations?
select `pickup location` ,count(*) from ride
group by `pickup location`
order by count(*) desc
limit 10;

#18. What are the top 10 drop locations?
select `drop location` ,count(*)from ride
group by `drop location`
order by count(*) desc 
limit 10;

#19. Which pickup location has the highest number of bookings?
select `pickup location`,count(*) from ride
group by `pickup location`
order by count(*) desc
limit 1;

# Revenue Analysis

#20. What is the total revenue generated by each vehicle type?
select sum(`Booking value`)as revenue,`vehicle type` from ride
group by `vehicle type`
order by revenue desc;

#21. What is the average booking value for each vehicle type?
select avg(`booking value`),`vehicle type` from ride
group by `vehicle type`
order by avg(`booking value`) desc;

#22. Which vehicle type generates the highest total booking value?
select `vehicle type`,sum(`booking value`) from ride
group by `vehicle type`
order by sum(`booking value`) desc
limit 1;

#23. What is the average driver rating?
select avg(`driver ratings`) from ride;

#24. What is the average customer rating?
select avg(`customer rating`) from ride;

#25. What is the average driver rating for each vehicle type?
select  avg(`driver ratings`) ,`vehicle type` from ride
group by `vehicle type`
order by avg(`driver ratings`)  desc;

#26. What is the average customer rating for each vehicle type?
select avg(`customer rating`),`vehicle type` from ride
group by `vehicle type`
order by avg(`customer rating`) desc;

# Payment Analysis
#27. Which payment method is used most frequently?
select `payment method`,count(*) from ride
where `payment method` is not null
group by `payment method`
order by count(*) desc
limit 1
;
#28. How many bookings were made using each payment method?
select count(*),`payment method` from ride
where `payment method` is not null
group by  `payment method`
order by count(*) desc;

#29. Which vehicle type is most popular?
select count(*),`vehicle type` from ride
group by  `vehicle type` 
order by count(*) desc;

#30. Which vehicle type generates the most revenue?
select `vehicle type`,sum(`booking value`) as revenue from ride
group by `vehicle type`
order by revenue desc
limit 1;

#31. What are the major reasons for cancellations?
select  `Reason for CancelLing by Customer`,count(*) from ride
where `Reason for CancelLing by Customer` != 'not cancelled'
group by `Reason for CancelLing by Customer`
order by count(*) desc
;
#32. Which locations have the highest booking demand?
select * from ride;
select `pickup location` ,count(*) from ride
group by `pickup location`
order by count(*) desc
limit 10;
